apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: donation-service
  name: donation-service
spec:
  ports:
    - name: "5100"
      port: 5100
      targetPort: 5100
  selector:
    io.kompose.service: donation-service
