apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: postgres-donation
  name: postgres-donation
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5432
  selector:
    io.kompose.service: postgres-donation
